### PR TITLE
Single file component

### PR DESCRIPTION
**Pull request by rsm0128**
### Feature
- Added inline Script and SCSS support.

### Usage
````
<div class="work-block">
    <h2 class="title">
        <?= $args['title']; ?>
    </h2>
</div>

<style>
    body {
        .work-block {
            border: 1px solid #000;
        }
    }
</style>
<style>
.work-block {
    h2 {
        &.title {
            font-weight: 700;
            color: red;
        }
    }
}
</style>
<script>
console.log(1);
</script>
<script>console.log(2);</script>
````

### CODE REVIEW

**Comment by drewbaker** [comment]
I was thinking that we'd have a `<template>` tag around the HTML structure... Do you think that makes sense?

As for the `<script>` tag, lets make it a `<script type='module'>`, but it can't be one giant `<script>` tag like you have, because variables will variables collide. It needs to be a separate script tag module per component. I think you want to loop through found scripts and add each one.

**Comment by rsm0128** [comment]
@drewbaker 
For the `template` tag, we can remove the tag with RegExp and just print the inner content. So no problem with `template` tag.
For `<script>`, OK, we can add as `<script type='module'>` per module in the same way with CSS code. The difference is we will add the script at footer section.

**Comment by drewbaker** [comment]
What is the line `$wp_components = array( 'header', 'footer' );` doing?

I'm nervous that this approach will be really slow performance... But I suppose lets try it out and see. Maybe we implement some sort of caching based on last file edit time..

**Comment by rsm0128** [comment]
@drewbaker Header and Footer are not real components. They have `wp_head()` and `wp_footer()` function which adds external CSS and JavaScript code. It causes issues and performance problem and that's why I excluded the layout related ones

**Comment by drewbaker** [comment]
OK but we have components called 'header' and 'footer' too... See first and last line here: https://github.com/drewbaker/wp-easy/blob/main/templates/home.php

So will we not be able to use single file components for them?

**Comment by rsm0128** [comment]
@drewbaker I added layout structure.

````
wp_easy_router([
    'home'              => '/',
    'work'              => '/work/',
    'work-detail'       => ['path' => '/work/:spot/', 'template' => 'work', 'layout' => 'layout1'],
    'reel'              => '/reel/',
]);
````
Default layout is `/layouts/default.php` and all the layout files are in `/layouts/` directory.

**Comment by drewbaker** [comment]
This is great!!!

I will say, I would really like to figure out a way to make the JS scripts into actual external JS files that are loaded as es6 modules, and with an importmap. The importmap allows for things like `import foo from 'wp-easy/main'` for example.

This would just have a much better performance, and be much closer to current best practices. Keeping the styles inline is fine, but do you think it's possible to save the scripts into a temp file, and rebuild when it's edited like the way SCSS does it?

See this for some reasoning of why the current inline way isn't ideal:
https://stackoverflow.com/questions/43817297/inlining-ecmascript-modules-in-html

Also, this should probably be a new PR.

**Comment by rsm0128** [comment]
@drewbaker I'm working on plugin implementation and refactoring. I'll work on it as soon as the plugin porting is finished

**Pull request closed without merging**
